services:
  postgres:
    container_name: datalens-postgres-${APP_ENV}
    image: akrasnov87/datalens-postgres:16
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB_US:-pg-us-db}", "-U", "${POSTGRES_USER:-pg-user}"]
      interval: 5s
      retries: 10
      start_period: 3s
    environment:
      HC: ${HC:-0}
      CONTROL_API_CRYPTO_KEY: "${CONTROL_API_CRYPTO_KEY:-ZGF0YWxlbnN1bnNlY3VyZWZlcm5ldGNyeXB0b2tleQo=}"
      US_ENDPOINT: ${US_ENDPOINT:-http://us:8080}
      #
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      #
      POSTGRES_USER: ${POSTGRES_USER:-pg-user}
      #
      POSTGRES_DB_COMPENG: ${POSTGRES_DB_COMPENG:-pg-compeng-db}
      POSTGRES_DB_AUTH: ${POSTGRES_DB_AUTH:-pg-auth-db}
      POSTGRES_DB_US: ${POSTGRES_DB_US:-pg-us-db}
      POSTGRES_DB_DEMO: ${POSTGRES_DB_DEMO:-pg-demo-db}
      POSTGRES_DB_META_MANAGER: ${POSTGRES_DB_META_MANAGER:-pg-meta-manager-db}
      POSTGRES_DB_TEMPORAL: ${POSTGRES_DB_TEMPORAL:-pg-temporal-db}
      POSTGRES_DB_TEMPORAL_VISIBILITY: ${POSTGRES_DB_TEMPORAL_VISIBILITY:-pg-temporal-visibility-db}
      #
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      #
      INIT_DEMO_DATA: ${INIT_DEMO_DATA:-1}
      INIT_DB_DEMO: ${INIT_DB_DEMO:-1}
      #
      INIT_DB_AUTH: ${INIT_DB_AUTH:-0}
      INIT_DB_META_MANAGER: ${INIT_DB_META_MANAGER:-1}
      INIT_DB_TEMPORAL: ${INIT_DB_TEMPORAL:-1}
      #
      INIT_EXTERNAL_POSTGRES: ${INIT_EXTERNAL_POSTGRES:-0}
    volumes:
      - db-postgres:/var/lib/postgresql/data
    networks:
      - default

  #
  control-api:
    container_name: datalens-control-api-${APP_ENV}
    image: akrasnov87/datalens-control-api:0.2253.0
    environment:
      BI_API_UWSGI_WORKERS_COUNT: 4
      RQE_FORCE_OFF: 1
      RQE_SECRET_KEY: ""
      #
      DL_CRY_ACTUAL_KEY_ID: KEY
      DL_CRY_KEY_VAL_ID_KEY: "${CONTROL_API_CRYPTO_KEY:-ZGF0YWxlbnN1bnNlY3VyZWZlcm5ldGNyeXB0b2tleQo=}"
      #
      US_HOST: http://us:8080
      #
      US_MASTER_TOKEN: ${US_MASTER_TOKEN:-us-master-token}
      #
      CONNECTOR_AVAILABILITY_VISIBLE: clickhouse,postgres,chyt,ydb,mysql,greenplum,mssql,appmetrica_api,metrika_api
      #
      AUTH__TYPE: ${AUTH_TYPE:-NONE}
      AUTH__JWT_ALGORITHM: 'PS256'
      AUTH__JWT_KEY: ${AUTH_TOKEN_PUBLIC_KEY:------BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+HICDZMfimMIiGdd0dPr\n2N3zxHOJqiVXuvUj/aBBS7c8760rJUh4344sP/0Gid558yH/v1MtzZ0R9w09v6gb\nSNrSiNwIUNGPhbnm9Jf+kMezsI/rkcIdoVm3KJ8CFUYy6MRPzW7iJmIVRHBb82v1\nmAYCCQFU6IRtFIa9hQ8wedWwxqXZekSNS+6NB37dmmQB9kz2E3MY+KRLigOh4i3p\nCZ1ti3HVvMa9Rlgk9FmoWExzub5ECChqwm+vn8yFXjYW7kUSClcV2xx4nbQWqjrR\nyyLk6W2BNOuCFVvz0j+5XkpLAt7tljtVZc+572HBEKpF2mAdmAip5NzeDhKqucJ+\nZQIDAQAB\n-----END PUBLIC KEY-----}
    volumes: []
    networks:
      - default

  #
  data-api:
    container_name: datalens-data-api-${APP_ENV}
    image: akrasnov87/datalens-data-api:0.2253.0
    environment:
      GUNICORN_WORKERS_COUNT: 5
      RQE_FORCE_OFF: 1
      CACHES_ON: 0
      MUTATIONS_CACHES_ON: 0
      RQE_SECRET_KEY: ""
      #
      DL_CRY_ACTUAL_KEY_ID: KEY
      DL_CRY_KEY_VAL_ID_KEY: "${CONTROL_API_CRYPTO_KEY:-ZGF0YWxlbnN1bnNlY3VyZWZlcm5ldGNyeXB0b2tleQo=}"
      #
      BI_COMPENG_PG_ON: 1
      BI_COMPENG_PG_URL: "postgres://${POSTGRES_USER:-pg-user}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB_COMPENG:-pg-compeng-db}${POSTGRES_ARGS:-}"
      #
      US_HOST: http://us:8080
      #
      US_MASTER_TOKEN: ${US_MASTER_TOKEN:-us-master-token}
      #
      AUTH__TYPE: ${AUTH_TYPE:-NONE}
      AUTH__JWT_ALGORITHM: 'PS256'
      AUTH__JWT_KEY: ${AUTH_TOKEN_PUBLIC_KEY:------BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+HICDZMfimMIiGdd0dPr\n2N3zxHOJqiVXuvUj/aBBS7c8760rJUh4344sP/0Gid558yH/v1MtzZ0R9w09v6gb\nSNrSiNwIUNGPhbnm9Jf+kMezsI/rkcIdoVm3KJ8CFUYy6MRPzW7iJmIVRHBb82v1\nmAYCCQFU6IRtFIa9hQ8wedWwxqXZekSNS+6NB37dmmQB9kz2E3MY+KRLigOh4i3p\nCZ1ti3HVvMa9Rlgk9FmoWExzub5ECChqwm+vn8yFXjYW7kUSClcV2xx4nbQWqjrR\nyyLk6W2BNOuCFVvz0j+5XkpLAt7tljtVZc+572HBEKpF2mAdmAip5NzeDhKqucJ+\nZQIDAQAB\n-----END PUBLIC KEY-----}
      COMMON_TIMEOUT_SEC: 120
    depends_on:
      postgres:
        condition: service_healthy
    volumes: []
    networks:
      - default
  
  us:
    container_name: datalens-us-${APP_ENV}
    image: akrasnov87/datalens-us:0.346.0
    environment:
      APP_INSTALLATION: opensource
      APP_ENV: prod
      APP_PORT: 8080
      #
      AUTH_ENDPOINT: http://auth:8080
      #
      MASTER_TOKEN: ${US_MASTER_TOKEN:-us-master-token}
      AUTH_MASTER_TOKEN: ${AUTH_MASTER_TOKEN:-auth-master-token}
      #
      POSTGRES_DSN_LIST: "postgres://${POSTGRES_USER:-pg-user}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB_US:-pg-us-db}${POSTGRES_ARGS:-}"
      US_SURPRESS_DB_STATUS_LOGS: 'true'
      #
      SKIP_INSTALL_DB_EXTENSIONS: 1
      #
      HC: ${HC:-0}
      #
      AUTH_ENABLED: ${AUTH_ENABLED:-false}
      AUTH_TOKEN_PUBLIC_KEY: ${AUTH_TOKEN_PUBLIC_KEY:------BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+HICDZMfimMIiGdd0dPr\n2N3zxHOJqiVXuvUj/aBBS7c8760rJUh4344sP/0Gid558yH/v1MtzZ0R9w09v6gb\nSNrSiNwIUNGPhbnm9Jf+kMezsI/rkcIdoVm3KJ8CFUYy6MRPzW7iJmIVRHBb82v1\nmAYCCQFU6IRtFIa9hQ8wedWwxqXZekSNS+6NB37dmmQB9kz2E3MY+KRLigOh4i3p\nCZ1ti3HVvMa9Rlgk9FmoWExzub5ECChqwm+vn8yFXjYW7kUSClcV2xx4nbQWqjrR\nyyLk6W2BNOuCFVvz0j+5XkpLAt7tljtVZc+572HBEKpF2mAdmAip5NzeDhKqucJ+\nZQIDAQAB\n-----END PUBLIC KEY-----}
    
      SQL_DEBUG: 'true'
      NODE_RPC_URL: ${NODE_RPC_URL:-http://us-auth/demo/rpc}
      USE_AUTH_DATA: 1
      POSTGRES_USER: ${POSTGRES_USER:-pg-user}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
    volumes: []
    networks:
      - default

  #
  us-auth:
    container_name: datalens-auth-${APP_ENV}
    image: akrasnov87/datalens-auth:0.2.4
    environment:
      APP_ENV: demo
      NODE_VPATH: /demo/
      #
      CONNECT_STR: "postgres://${POSTGRES_USER:-pg-user}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB_US:-pg-us-db}${POSTGRES_ARGS:-}"
      PROJECT_ID: ${PROJECT_ID:-datalens-demo}
      BUDIBASE_URI: ${BUDIBASE_URI:-}
      NODE_THREAD: 2
      VERSION_CONTAINER: 0.2.4
      AUTH_KEY_MODE: ${AUTH_KEY_MODE:-false}
    networks:
      - default
  
  #
  ui:
    container_name: datalens-ui-${APP_ENV}
    image: akrasnov87/datalens-ui:0.2864.0
    environment:
      APP_MODE: full
      APP_ENV: production
      APP_INSTALLATION: opensource
      #
      AUTH_POLICY: disabled
      #
      US_ENDPOINT: http://us:8080
      #AUTH_ENDPOINT: http://auth:8080
      BI_API_ENDPOINT: http://control-api:8080
      BI_DATA_ENDPOINT: http://data-api:8080
      #
      US_MASTER_TOKEN: ${US_MASTER_TOKEN:-us-master-token}
      #
      RELEASE_VERSION: '2.1.0'
      #
      HC: ${HC:-0}
      YANDEX_MAP_ENABLED: ${YANDEX_MAP_ENABLED:-0}
      YANDEX_MAP_TOKEN: ${YANDEX_MAP_TOKEN:-}
      #
      AUTH_ENABLED: ${AUTH_ENABLED:-false}
      AUTH_MASTER_TOKEN: ${AUTH_MASTER_TOKEN:-auth-master-token}
      AUTH_TOKEN_PUBLIC_KEY: ${AUTH_TOKEN_PUBLIC_KEY:------BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+HICDZMfimMIiGdd0dPr\n2N3zxHOJqiVXuvUj/aBBS7c8760rJUh4344sP/0Gid558yH/v1MtzZ0R9w09v6gb\nSNrSiNwIUNGPhbnm9Jf+kMezsI/rkcIdoVm3KJ8CFUYy6MRPzW7iJmIVRHBb82v1\nmAYCCQFU6IRtFIa9hQ8wedWwxqXZekSNS+6NB37dmmQB9kz2E3MY+KRLigOh4i3p\nCZ1ti3HVvMa9Rlgk9FmoWExzub5ECChqwm+vn8yFXjYW7kUSClcV2xx4nbQWqjrR\nyyLk6W2BNOuCFVvz0j+5XkpLAt7tljtVZc+572HBEKpF2mAdmAip5NzeDhKqucJ+\nZQIDAQAB\n-----END PUBLIC KEY-----}
    
      FLAT_TABLE_ROWS_LIMIT: 100000
      FETCHING_TIMEOUT_SEC: 120
      UNITED_STORAGE_CONFIG_LOADED_TIMEOUT: 10000
      EXPORT_DASH_EXCEL: ${EXPORT_DASH_EXCEL:-false}
      OIDC: ${OIDC:-false}
      OIDC_ISSUER: ${OIDC_ISSUER}
      OIDC_BASE_URL: ${OIDC_BASE_URL}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_SECRET: ${OIDC_SECRET}
      OIDC_NAME: ${OIDC_NAME:-OIDC}

      HC_ENDPOINT: ${HC_ENDPOINT:-}
      HC_PROTOCOL: ${HC_PROTOCOL:-https}
    depends_on:
      - us
    volumes: []
    ports:
      - ${UI_PORT:-8080}:8080
    networks:
      - default

#
volumes:
  db-postgres:
#
networks:
  default:
