services:
  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
    ports:
      - 5432:5432
    networks:
      - default

  control-api:
    extends:
      file: docker-compose.yaml
      service: control-api
    ports:
      - 8010:8080
    networks:
      - default

  data-api:
    extends:
      file: docker-compose.yaml
      service: data-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8020:8080
    networks:
      - default

  us:
    extends:
      file: docker-compose.yaml
      service: us
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3030:8080
    networks:
      - default

  us-auth:
    extends:
      file: docker-compose.yaml
      service: us-auth
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8088:80
    networks:
      - default

  ui:
    extends:
      file: docker-compose.yaml
      service: ui
    depends_on:
      - us
    networks:
      - default

volumes:
  db-postgres:

networks:
  default:
