services:
  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
    ports:
      - 5432:5432
    networks:
      - default

  temporal:
    extends:
      file: docker-compose.yaml
      service: temporal
    environment:
      TEMPORAL_AUTH_ENABLED: false
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 7233:7233
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-file: "3"  # количество файлов
        max-size: "5m" # размер файла лога

  temporal-ui:
    container_name: datalens-temporal-ui-${APP_ENV}
    image: ghcr.io/datalens-tech/temporal-ui:2.34.0
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_AUTH_ENABLED: false
    depends_on:
      - temporal
    ports:
      - 8233:8080
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-file: "3"  # количество файлов
        max-size: "5m" # размер файла лога

  control-api:
    extends:
      file: docker-compose.yaml
      service: control-api
    ports:
      - 8010:8080
    networks:
      - default

  data-api:
    extends:
      file: docker-compose.yaml
      service: data-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8020:8080
    networks:
      - default

  us:
    extends:
      file: docker-compose.yaml
      service: us
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8030:8080
    networks:
      - default

  ui-api:
    extends:
      file: docker-compose.yaml
      service: ui-api
    depends_on:
      - us
    ports:
      - 3040:8080
    networks:
      - default

  meta-manager:
    extends:
      file: docker-compose.yaml
      service: meta-manager
    depends_on:
      temporal:
        condition: service_healthy
      ui-api:
        condition: service_started
    ports:
      - 3050:8080
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-file: "3"  # количество файлов
        max-size: "5m" # размер файла лога

  us-auth:
    extends:
      file: docker-compose.yaml
      service: us-auth
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8088:80
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-file: "3"  # количество файлов
        max-size: "5m" # размер файла лога

  ui:
    extends:
      file: docker-compose.yaml
      service: ui
    depends_on:
      - us
    networks:
      - default

volumes:
  db-postgres:
    name: datalens-volume-${APP_ENV}

networks:
  default: