services:
  pg-compeng:
    container_name: datalens-pg-compeng-${APP_ENV}
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres

  control-api:
    container_name: datalens-control-api-${APP_ENV}
    image: akrasnov87/datalens-control-api:0.2226.0
    environment:
      BI_API_UWSGI_WORKERS_COUNT: 4
      CONNECTOR_AVAILABILITY_VISIBLE: "clickhouse,postgres,chyt,ydb,mysql,greenplum,mssql"
      RQE_FORCE_OFF: 1
      DL_CRY_ACTUAL_KEY_ID: key_1
      DL_CRY_KEY_VAL_ID_key_1: "h1ZpilcYLYRdWp7Nk8X1M1kBPiUi8rdjz9oBfHyUKIk="
      RQE_SECRET_KEY: ""
      US_HOST: "http://host.docker.internal:8083"
      US_MASTER_TOKEN: "fake-us-master-token"
    ports:
      - 8081:8080
    depends_on:
      - us
    extra_hosts:
      - "host.docker.internal:host-gateway"

  data-api:
    container_name: datalens-data-api-${APP_ENV}
    image: akrasnov87/datalens-data-api:0.2226.0
    environment:
      GUNICORN_WORKERS_COUNT: 5
      RQE_FORCE_OFF: 1
      CACHES_ON: 0
      MUTATIONS_CACHES_ON: 0
      RQE_SECRET_KEY: ""
      DL_CRY_ACTUAL_KEY_ID: key_1
      DL_CRY_KEY_VAL_ID_key_1: "h1ZpilcYLYRdWp7Nk8X1M1kBPiUi8rdjz9oBfHyUKIk="
      BI_COMPENG_PG_ON: 1
      BI_COMPENG_PG_URL: "postgresql://postgres:postgres@pg-compeng:5432/postgres"
      US_HOST: "http://host.docker.internal:8083"
      US_MASTER_TOKEN: "fake-us-master-token"
      COMMON_TIMEOUT_SEC: 120
    ports:
      - 8082:8080
    depends_on:
      - us
      - pg-compeng
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pg-demo-connection:
    container_name: datalens-pg-demo-connection-${APP_ENV}
    image: postgres:16-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    volumes:
      - ./pg-demo-connection/data:/var/lib/postgresql/data
      - ./pg-demo-connection/init:/docker-entrypoint-initdb.d

  pg-us:
    container_name: datalens-pg-us-${APP_ENV}
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: us-db-ci_purgeable
      POSTGRES_USER: us
      POSTGRES_PASSWORD: us
    volumes:
      - ./metadata:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  us:
    container_name: datalens-us-${APP_ENV}
    image: akrasnov87/datalens-us:0.331.0
    depends_on:
      - pg-us
    environment:
      APP_INSTALLATION: "opensource"
      APP_ENV: "prod"
      MASTER_TOKEN: "fake-us-master-token"
      POSTGRES_DSN_LIST: ${METADATA_POSTGRES_DSN_LIST:-postgres://us:us@pg-us:5432/us-db-ci_purgeable}
      SKIP_INSTALL_DB_EXTENSIONS: ${METADATA_SKIP_INSTALL_DB_EXTENSIONS:-0}
      USE_DEMO_DATA: ${USE_DEMO_DATA:-1}
      USE_AUTH_DATA: ${USE_AUTH_DATA:-1}
      SQL_DEBUG: true
      US_SURPRESS_DB_STATUS_LOGS: true
      HC: ${HC:-0}
      NODE_EXTRA_CA_CERTS: /certs/root.crt
      NODE_RPC_URL: ${NODE_RPC_URL:-http://us-auth/demo/rpc}
    ports:
      - "8083:8083"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./certs:/certs

  us-auth:
    container_name: datalens-auth-${APP_ENV}
    image: akrasnov87/datalens-auth:0.2.4
    ports:
      - "5001:80"
    environment:
      APP_ENV: demo
      NODE_VPATH: /demo/
      CONNECT_STR: ${METADATA_POSTGRES_DSN_LIST:-postgres://us:us@pg-us:5432/us-db-ci_purgeable}
      PROJECT_ID: ${PROJECT_ID:-datalens-demo}
      BUDIBASE_URI: ${BUDIBASE_URI:-}
      NODE_THREAD: 2
      VERSION_CONTAINER: 0.2.4
      AUTH_KEY_MODE: ${AUTH_KEY_MODE:-false}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  datalens:
    container_name: datalens-ui-${APP_ENV}
    image: akrasnov87/datalens-ui:0.2752.0
    ports:
      - ${UI_PORT:-8080}:8080
    depends_on:
      - us-auth
      - us
      - control-api
      - data-api
      - pg-demo-connection
    environment:
      APP_MODE: "full"
      APP_ENV: "production"
      APP_INSTALLATION: "opensource"
      AUTH_POLICY: "disabled"
      US_ENDPOINT: "http://host.docker.internal:8083"
      BI_API_ENDPOINT: "http://host.docker.internal:8081"
      BI_DATA_ENDPOINT: "http://host.docker.internal:8082"
      US_MASTER_TOKEN: "fake-us-master-token"
      NODE_EXTRA_CA_CERTS: "/usr/local/share/ca-certificates/cert.pem"
      FLAT_TABLE_ROWS_LIMIT: 100000
      FETCHING_TIMEOUT_SEC: 120
      UNITED_STORAGE_CONFIG_LOADED_TIMEOUT: 10000
      EXPORT_DASH_EXCEL: ${EXPORT_DASH_EXCEL:-false}
      HC: ${HC:-0}
      #HC_ENDPOINT: ${HC_ENDPOINT:-localhost:8080/highcharts}
      #HC_PROTOCOL: ${HC_PROTOCOL:-http}
      OIDC: ${OIDC:-false}
      OIDC_ISSUER: ${OIDC_ISSUER}
      OIDC_BASE_URL: ${OIDC_BASE_URL}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_SECRET: ${OIDC_SECRET}
      OIDC_NAME: ${OIDC_NAME:-OIDC}
      YANDEX_MAP_ENABLED: ${YANDEX_MAP_ENABLED:-0}
      YANDEX_MAP_TOKEN: ${YANDEX_MAP_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"